default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: yt_scraper_development

test: &test
  <<: *default
  database: yt_scraper_test

production:
  <<: *default
  database: yt_scraper
